name: Test Packer Format and Validation

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  packer_format_and_validation:
    name: Packer Format and Validation Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create zip archive
        run: zip -r webapp.zip .

      - name: Install Packer
        run: sudo apt-get update && sudo apt-get install -y packer && cd packer && pwd
      - name: Packer Init
        run: packer init packer

      - name: Packer Format
        run: |
          # Use the find command to locate all .pkr.hcl files in the "packer" folder
          # and apply "packer fmt" to each of them
          find packer -name "*.pkr.hcl" -exec packer fmt -check -diff {} \;
          if [ $? -ne 0 ]; then
            echo "Packer format check failed. Run 'packer fmt' to fix."
            exit 1
          fi

      - name: Validate Packer Template
        run: |
          # Use the find command to locate all .pkr.hcl files in the "packer" folder
          # and validate each of them using "packer validate"
          find packer -name "*.pkr.hcl" -exec packer validate {} \;
          if [ $? -ne 0 ]; then
            echo "Packer validation check failed."
            exit 1
          fi
